# Automatically generated by: ros2nix
{
  nix-ros-overlay ? builtins.fetchTarball "https://github.com/lopsided98/nix-ros-overlay/archive/master.tar.gz",
  pkgs ? import nix-ros-overlay { },
  rosDistro ? "rolling",
  extraPkgs ? { },
  extraPaths ? [ ],
  withPackages ? _: [ ],
  extraShellHook ? "",
}:
pkgs.mkShell {
  name = "ros2nix ${rosDistro} shell";
  packages = [
    (pkgs.rosPackages.${rosDistro}.buildEnv {
      wrapPrograms = false;
      paths =
        [
          pkgs.colcon
          pkgs.rosPackages.${rosDistro}.ros-core

          # Work around https://github.com/lopsided98/nix-ros-overlay/pull/624
          pkgs.rosPackages.${rosDistro}.ament-cmake-core
          pkgs.rosPackages.${rosDistro}.python-cmake-module
        ]
        ++ (
          with pkgs;
          with pkgs.rosPackages.${rosDistro};
          with extraPkgs;
          [
            # Dependencies from package.xml files
            ament-cmake
            ament-cmake-core
            ament-cmake-gtest
            ament-cmake-pytest
            ament-cmake-python
            ament-index-python
            ament-lint-auto
            ament-lint-common
            boost
            camera-calibration-parsers
            camera-info-manager
            cupy-cuda12x
            cv-bridge
            eigen
            eigen3-cmake-module
            filters
            gazebo-ros-pkgs
            geometry-msgs
            image-transport
            joint-state-publisher
            joint-state-publisher-gui
            launch-ros
            launch-testing
            launch-testing-ament-cmake
            launch-testing-ros
            message-filters
            nav-msgs
            nav2-common
            nav2-costmap-2d
            nav2-msgs
            navigation2
            numpy-lessthan-2
            octomap
            octomap-msgs
            octomap-rviz-plugins
            octomap-server
            onetbb
            pcl
            pluginlib
            python3
            python3Packages.opencv4
            python3Packages.pytest
            python3Packages.ruamel_yaml
            python3Packages.scipy
            python3Packages.shapely
            python3Packages.transforms3d
            qt5.qtbase
            rclcpp
            rclpy
            rcutils
            robot-state-publisher
            ros2-numpy
            rosbag2-cpp
            rosbag2-py
            rosbag2-storage-default-plugins
            rosidl-default-generators
            rosidl-default-runtime
            rviz-common
            rviz-ogre-vendor
            rviz-rendering
            rviz2
            sensor-msgs
            simple-parsing
            slam-toolbox
            std-msgs
            std-srvs
            teleop-twist-keyboard
            tf-transformations
            tf2
            tf2-geometry-msgs
            tf2-ros
            turtlebot3-msgs
            turtlebot3-teleop
            visualization-msgs
            xacro
            yaml-cpp
          ]
        )
        ++ builtins.attrValues extraPkgs
        ++ extraPaths
        ++ withPackages (pkgs // pkgs.rosPackages.${rosDistro});
      }
    )
  ];
  shellHook = ''
    # Setup ROS 2 shell completion. Doing it in direnv is useless.
    if [[ ! $DIRENV_IN_ENVRC ]]; then
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete ros2)"
        eval "$(${pkgs.python3Packages.argcomplete}/bin/register-python-argcomplete colcon)"
    fi
  '' + extraShellHook;
}
