# Automatically generated by: ros2nix
{ lib, buildRosPackage, ament-cmake, ament-cmake-python, ament-lint-auto, ament-lint-common, geometry-msgs, grid-map-core, grid-map-msgs, grid-map-ros, joint-state-publisher, joint-state-publisher-gui, launch-ros, nav2-common, navigation2, python3, rclpy, robot-state-publisher, rviz2, sensor-msgs, slam-toolbox, teleop-twist-keyboard, xacro }:
buildRosPackage rec {
  pname = "ros-rolling-shredder-description";
  version = "0.0.1";

  src = ./.;

  buildType = "ament_cmake";
  buildInputs = [ ament-cmake ament-cmake-python ];
  checkInputs = [ ament-lint-auto ament-lint-common ];
  propagatedBuildInputs = [ geometry-msgs grid-map-core grid-map-msgs grid-map-ros joint-state-publisher joint-state-publisher-gui launch-ros nav2-common navigation2 python3 rclpy robot-state-publisher rviz2 sensor-msgs slam-toolbox teleop-twist-keyboard xacro ];
  nativeBuildInputs = [ ament-cmake ament-cmake-python ];

  meta = {
    description = "URDF description for tracked vehicle";
    license = with lib.licenses; [ asl20 ];
  };
}
